import Head from 'next/head'
import Image from 'next/image'

import Layout from '../components/Layout/Layout'
import MoreArrow from '../components/Links/MoreArrow'

export default function Home({test}) {


  
  return (
    <Layout>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className='min-h-screen w-full relative flex'>
        
        <Image
        src="/image/del/home-hero.jpg"
        layout="fill"
        objectFit="cover"
        alt=""/>

        <h1 className="font-display text-[100px] leading-[120px] text-white m-auto relative text-center">Find yourself in our <br/><em>neighbourhood?</em></h1>
      </div>
        
      <div className="container mx-auto">

        <div className="flex">
          <div className="w-6/12 max-w-[598px] mx-auto px-14 py-9 bg-blue-1 text-white text-center min-h-[700px] flex flex-col">
            <h2 className="uppercase">Escapism</h2>
            <div className="m-auto max-w-[416px]">
              <p>Etiam sed lorem eleifend, consequat felis nec, bibendum ante. Pellentesque dui urna, imperdiet lacinia lacus at?
Etiam sed lorem eleifend, consequat felis nec, bibendum ante. Pellentesque dui urna, imperdiet lacinia lacus at?? {test}</p>
            </div>
            <div className="ml-auto">
              <MoreArrow title="Our Story"/>
            </div>
          </div>
        </div>

        <p className="font-display text-[200px] leading-[200px]">Lose <br/><em>yourself</em> <br/>in the <br/><em>moment</em></p>
      </div>

    </Layout>
  )
}

export async function getStaticProps({ params }) {
  return {
    props: {
      test: "fhiidi"
    },
    revalidate: 1,
  };
}
